// Copyright 2026 JumpProto contributors.
// SPDX-License-Identifier: Apache-2.0

import assert from 'node:assert/strict';
import test from 'node:test';
import { extractProtoPathFromPbGo, findProtoSymbolMatch } from './core';

test('extractProtoPathFromPbGo parses protoc-gen-go header', () => {
  const pb = `// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: api/activity/ac_2603_canghai_god.proto\n\npackage x\n`;
  assert.equal(extractProtoPathFromPbGo(pb), 'api/activity/ac_2603_canghai_god.proto');
});

test('findProtoSymbolMatch finds message', () => {
  const proto = `syntax = "proto3";\n\nmessage TestDataReq {\n  repeated string list = 1;\n}\n`;
  const m = findProtoSymbolMatch(proto, 'TestDataReq');
  assert.ok(m);
  assert.equal(m?.kind, 'message');
  assert.equal(proto.slice(m!.startOffset, m!.endOffset), 'TestDataReq');
});

test('findProtoSymbolMatch prefers message over rpc/service', () => {
  const proto = `service S {\n  rpc TestDataReq (A) returns (B);\n}\nmessage TestDataReq { }\n`;
  const m = findProtoSymbolMatch(proto, 'TestDataReq');
  assert.ok(m);
  assert.equal(m?.kind, 'message');
});

test('findProtoSymbolMatch matches go field names that preserve underscore before digits', () => {
  const proto = `message TaskPageResp {\n  bool show_task_5 = 2;\n}\n`;
  const m = findProtoSymbolMatch(proto, 'ShowTask_5', 'TaskPageResp');
  assert.ok(m);
  assert.equal(m?.kind, 'field');
  assert.equal(proto.slice(m!.startOffset, m!.endOffset), 'show_task_5');
});

test('findProtoSymbolMatch finds fields after nested declarations', () => {
  const proto = `message Outer {\n  message Inner {\n    string nested = 1;\n  }\n  string target_field = 2;\n}\n`;
  const m = findProtoSymbolMatch(proto, 'TargetField', 'Outer');
  assert.ok(m);
  assert.equal(m?.kind, 'field');
  assert.equal(proto.slice(m!.startOffset, m!.endOffset), 'target_field');
});

test('findProtoSymbolMatch maps generated nested Go container names to proto messages', () => {
  const proto = `message Outer {\n  message Inner {\n    string target_field = 1;\n  }\n}\n`;
  const m = findProtoSymbolMatch(proto, 'TargetField', 'Outer_Inner');
  assert.ok(m);
  assert.equal(m?.kind, 'field');
  assert.equal(proto.slice(m!.startOffset, m!.endOffset), 'target_field');
});
